== Bruksanvisning til denne modenhetsmodellen [[bruksanvisning]] 

=== Generelt [[bruksanvisning-generelt]]

*	Dersom modenheten varierer mellom ulike organisasjonsenheter i en virksomhet, bør en ikke bestrebe seg på å komme fram til en totalscorefootnote:[Med totalscore menes snitt/median/e.l. av scorene for ulike organisasjonsenheter. Scorene for de ulike organisasjonsenhetene kan godt sammenstilles i samme diagram.], men heller vurdere modenheten i hver enhet for seg. 
* For oversikt over og beskrivelse av datasett, finnes det i dag ingen obligatoriske nasjonale standarder. Det overlates derfor til de vurderende virksomheter å avgjøre hva som er nødvendig og tilstrekkelig. Det mest relevante er å ta utgangspunkt i hva en selv ville trenge av oversikt og beskrivelse, for å kunne vurdere egnethet av et datasett beskrevet av andre. Dersom en ønsker å relatere vurderingen til en standard, kan en bruke https://data.norge.no/specification/dcat-ap-no["Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO) &#x29C9;", window="_blank", role="ext-link"] som er en anbefalt forvaltningsstandard. I og med at det nå ikke er krav om å vurdere modenhet iht. noen standard, må en regne med at egen score kan reduseres senere dersom det en nå oppfatter som «tilstrekkelig», ikke oppfyller kravene i en framtidig standard.  
*	Det er noe avhengighet mellom aksene selv om den er forsøkt redusert. Avhengighetene er beskrevet mer detaljert nedenfor i tilknytning til de enkelte aksene.  

=== Ordforklaringer [[ordforklaring]]
*	[[prosedyrer]]**Prosedyre**: Med prosedyre menes det her dokumentert og repeterbar fremgangsmåte (for å utføre en gitt oppgave). Eksempler på prosedyrer: Prosedyrer ifm. 
informasjonssikkerhetsarbeid.  
**	Det er i denne modenhetsmodellen kun spørsmål om prosedyrer for å etablere og systematisk vedlikeholde oversikt over og beskrivelse av egne datasett.  
** [[vedtatte-prosedyrer]]**Vedtatte prosedyrer**: Prosedyrer som i henhold til en eller annen policy i virksomheten bør (valgfritt) eller skal (obligatorisk) brukes.  
*	[[datasett]]**Datasett** er definert som «samling av data». I vår sammenheng kan vi også si at dette er data som er samlet/skapt for å gi informasjon om et spesifikt fenomen, f.eks. «Sysselsatte etter kjønn og alder». Med formål datadeling, kan vi også si at et datasett er en samling av dataelementene som samlet kan deles med andre.  
**	[[relevante-datasett]]**Relevante datasett**: Det er opp til virksomheten selv å definere, ut fra gitte formål, hva som er relevante datasett. For å kunne følge modenhetsutviklingen over tid er det hensiktsmessig å være presis på hva som til enhver tid er definert som relevant. Dersom f.eks. formålet er informasjonsdeling, er alle datasett som virksomheten kan dele med andre, relevante.  
*	[[oversikt-over-datasett]]**Oversikt over datasett**: En fortegnelse/liste over de datasett virksomheten har identifisert som <<relevante-datasett, relevante>>.  
**	Hensikten er at andre skal kunne oppdage datasett som din virksomhet forvalter.  
** Som nevnt i et tidligere punkt finnes det p.t. ingen nasjonal obligatorisk standard for oversikt over datasett. Man bør imidlertid i oversikten typisk ha med følgende for hvert datasett: tittel, en kort beskrivelse av innhold, eier, kontaktperson og hyppighet for tilgjengeliggjøring. Se ellers https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"] som p.t. er en anbefalt forvaltningsstandard for beskrivelse av datasett, datatjenester og datakataloger.  
*	[[beskrivelse-av-datasett]]**Beskrivelse av datasett**: Beskrivelse av hva datasettet er (betyr), hva det inneholder, hvordan det er skapt osv.  
**	Med beskrivelse av datasett, mener vi i vår sammenheng en mer detaljert beskrivelse enn det som gis i <<oversikt-over-datasett, oversikten over datasett>>. Hensikten er at andre skal kunne evaluere/vurdere egnethet av datasett som din virksomhet forvalter, til bruk i en eller annen spesifikk sammenheng. Denne beskrivelsen må derfor være tilstrekkelig til at potensielle brukere skjønner hva datasettet inneholder og hva de ulike innholdselementenefootnote:[Det er vanskelig å finne en samlebetegnelse for dette, følgende termer er f.eks. ofte brukt: variabler, dataelementer, egenskaper, attributter.] i datasettet betyr. Brukeren må ut fra beskrivelsen kunne vurdere om dette datasettet er aktuelt i en eller annen spesifikk sammenheng. Beskrivelse bør inneholde navnet på alle relevante innholdselementene i datasettet, definisjoner på hva de betyr (hvordan er f.eks. inntekt definert i dette datasettet) og ev. kodeverk som brukes (f.eks. hva betyr det at verdien for kjønn er 1). Dersom det brukes ulike måleenheter, f.eks. kroner og 1000 kroner, er også dette viktig å dokumentere. 

**  https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"] dekker ikke behov for i tilstrekkelig grad å beskrive innholdselementene i et datasett. Det er imidlertid mulig å relatere en datasettbeskrivelse til en informasjonsmodell som datasettet er i samsvar med, og som beskriver innholdselementene i datasettet. Det er også etablert en  https://data.norge.no/specification/modelldcat-ap-no[Spesifikasjon for beskrivelse av informasjonsmodeller (ModellDCAT-AP-NO) &#x29C9;, window="_blank", role="ext-link"], for å gjøre tilgjengelig informasjonsmodeller i maskinlesbare RDF-formater.   

*	[[strukturert-form]]**Strukturert form**: Oversikten/beskrivelsen er utformet i henhold til en definert struktur.  

**	https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO  &#x29C9;, window="_blank", role="ext-link"] er p.t. en anbefalt forvaltningsstandard  for for beskrivelse av datasett, datatjenester og datakataloger.   

** https://data.norge.no/specification/skos-ap-no-begrep[Forvaltningsstandard for begrepsbeskrivelser (SKOS-AP-NO-Begrep) &#x29C9;, window="_blank", role="ext-link"] er p.t. en anbefalt forvaltningsstandard for å dokumentere definisjon av begreper i en strukturert form. 

** https://data.norge.no/specification/modelldcat-ap-no[ModellDCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"] er p.t. en felles spesifikasjon for beskrivelse og tilgjengeliggjøring av informasjonsmodeller. 

*	[[systematisk-vedlikeholdt]]**Systematisk vedlikeholdt (eller tilgjengeliggjort)**: Oversikt over og/eller beskrivelse av datasett er ikke blitt etablert (eller tilgjengeliggjort) som en engangsjobb, men det er rutiner som sikrer at oversikten/beskrivelsen blir vedlikeholdt (eller tilgjengeliggjort).  

*	[[tilgjengeliggjort]]**Tilgjengeliggjort**: Denne modenhetsmodellen fokuserer på tilgjengeliggjøring for eksterne brukere. Dette betyr at eksterne brukere skal kunne få fatt i oversikten/beskrivelsen. For å få full score langs tilgjengeliggjøringsaksene i denne modenhetsmodellen, skal tilgjengeliggjøring skje via et bestemt sted.

** Digitaliseringsrundskrivet sier at virksomheten skal registrere datasett i Felles datakatalog (https://data.norge.no[data.norge.no &#x29C9;, window="_blank", role="ext-link"]). 
** https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO  &#x29C9;, window="_blank", role="ext-link"] er basert på https://www.w3.org/RDF/[RDF &#x29C9;, window="_blank", role="ext-link"], og tilgjengeliggjøring av datasettbeskrivelser og -oversikter i henhold til DCAT-AP-NO vil derfor skje i maskinlesbare RDF-formater.

*	**Virksomhet**: Ordet «virksomhet» i dette dokumentet dekker også «del av en virksomhet» eller »virksomhetsenhet», når hver virksomhetsenhet vurderes for seg.  

=== Aksen Prosedyrer  [[aksen-prosedyrer]]
*	**Score 0** ( = ikke vurdert) brukes når det ikke er foretatt noen vurdering av denne aksen. 
*	**Score 1** ( = ingen) brukes når det ikke er noen <<prosedyrer, prosedyrer>> for arbeid med <<oversikt-over-datasett, oversikt>> over og <<beskrivelse-av-datasett, beskrivelse>> av <<datasett, datasett>>.  
*	**Score 2** ( = ad hoc) brukes når det brukes egne ikke-<<vedtatte-prosedyrer, vedtatte prosedyrer>> på ad hoc basis.  
**	Eksempel på bruk av score 2: «Bare Prosjektet P (20xx-20yy) som brukte en egenutviklet metode for å beskrive hvilke datasett som var brukt i tjenestene som ble utviklet i prosjektet.» 
*	**Score 3** ( = noen) brukes når virksomheten har <<vedtatte-prosedyrer, vedtatt>> minst én av de nødvendige <<prosedyrer, prosedyrene>> for bruk i arbeid med <<oversikt-over-datasett, oversikt>> over og <<beskrivelse-av-datasett, beskrivelse>> av egne <<datasett, datasett>>.  
**	For å komme fra score 2 til score 3: Virksomheten må selv vurdere hva som er nødvendig og tilstrekkelig av <<prosedyrer, prosedyrer>> for å sikre at <<oversikt-over-datasett, oversikt>> over og <<beskrivelse-av-datasett, beskrivelse>> av egne <<datasett, datasett>> blir <<systematisk-vedlikeholdt, systematisk>> etablert og vedlikeholdt. Score 3 brukes når minst én av <<prosedyrer, prosedyrene>> som er vurdert nødvendig er etablert og <<vedtatte-prosedyrer, vedtatt>> tas i bruk i virksomheten.  
** Eksempel på bruk av score 3: «Prosedyren R for beskrivelse av datasett er på plass og allerede brukt i fagområde F. Det mangler imidlertid prosedyrer for å ha en samlet oversikt over alle relevante datasett i hele virksomheten.» 
*	**Score 4** ( = alle) brukes når alle <<prosedyrer, prosedyrer>> som virksomheten har vurdert som nødvendige, er etablert og <<vedtatte-prosedyrer, vedtatt>> tas i bruk i virksomheten.  
** For å komme fra score 3 til score 4: Virksomheten vurderer det slik at det som er <<vedtatte-prosedyrer, vedtatt>> brukt av <<prosedyrer, prosedyrer>>, er tilstrekkelig til at virksomheten klarer å holde en <<systematisk-vedlikeholdt, systematisk>> oppdatert <<oversikt-over-datasett, oversikt>> over og <<beskrivelse-av-datasett, beskrivelse>> av egne <<datasett, datasett>>.  
**	Avhengig av kompleksiteten av virksomheten, kan avstanden mellom score 3 og 4 være liten for noen virksomheter og stor for noen andre. 
** Eksempel på bruk av score 4: «Et rammeverk for informasjonsforvaltning som bl.a. 
inneholder alle nødvendige prosedyrer er på plass. Dette er også en del av felles systemutviklingsmetode.»  

=== Aksen Oversikt over datasett [[aksen-dataoversikt]] 

*	Se https://www.digdir.no/informasjonsforvaltning/veileder-orden-i-eget-hus/2716[Veileder for orden i eget hus &#x29C9;, window="_blank", role="ext-link"], for forskjell og sammenheng mellom Oversikt over datasett og Beskrivelse av datasett.  
*	**Score 0** ( = ikke vurdert) brukes når det ikke er foretatt noen vurdering av denne aksen. 
*	**Score 1** ( = ingen) brukes når virksomheten har ingen <<oversikt-over-datasett, oversikt>> over egne <<datasett, datasett>>.  
*	**Score 2** ( = ad hoc) brukes når det finnes <<oversikt-over-datasett, oversikt>> over (noen) <<datasett, datasett>> i virksomheten, men oversikten er ikke i <<strukturert-form, strukturert form>> og ikke <<systematisk-vedlikeholdt, vedlikeholdt systematisk>>.  
**	Eksempel på bruk av score 2: «Vi har diverse oversikter over datasett, men ingen enhetlig dokumentasjon eller et felles sted hvor dette finnes.»  
*	**Score 3** ( = noen) brukes når virksomheten har <<oversikt-over-datasett, oversikt>> over noen (men ikke alle) <<relevante-datasett, relevante datasett>>, og at oversikten er i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>. 
**	For å komme fra score 2 til score 3: Virksomheten har <<oversikt-over-datasett, oversikt>> over minst ett av sine <<datasett, datasett>>, og oversikten er i en <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>.  
** Eksempel på bruk av score 3: «Fagområde F bruker DCAT-AP-NO som mal for å holde oversikt over alle sine datasett, og oversikten gjennomgås årlig. Mangler oversikt over datasett fra andre fagområder.» 
*	**Score 4** ( = alle) brukes når virksomheten har <<oversikt-over-datasett, oversikt>>  over alle <<relevante-datasett, relevante datasett>>, og at oversikten er i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>. 
**	For å komme fra score 3 til score 4: Score 4 brukes når virksomheten mener å ha tilstrekkelig <<oversikt-over-datasett, oversikt>> over alle sine <<relevante-datasett, relevante datasett>>, og at oversikten er i <<strukturert-form, strukturert form>>  og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>.  
** Avhengig av kompleksiteten av virksomheten, og hva virksomheten selv vurderer som <<relevante-datasett, relevante datasett>>, kan avstanden mellom score 3 og 4 være liten for noen virksomheter og stor for noen andre.  
** Eksempel på bruk av score 4: «I forbindelse med risikovurdering i fjor kartla vi alle datasett i hele virksomheten. Oversikten er nå utformet i samsvar med DCAT-AP-NO. Seksjon S har fått ansvar for å oppdatere oversikten årlig.» 

=== Aksen Tilgjengelighet av oversikt over datasett  [[aksen-tilgjengelighet-dataoversikt]]
*	Det er tilgjengeliggjøring av [.underline]#oversikt# over datasett denne aksen handler om, ikke tilgjengeliggjøring av selve datasettene. Det er dessuten tilgjengelighet for eksterne brukere det her spørres om.  
*	Det er avhengighet mellom <<aksen-dataoversikt, aksen Oversikt over datasett>> og denne aksen Tilgjengelighet av oversikt over datasett - dersom vi ikke har noen oversikt, har vi heller ingenting å tilgjengeliggjøre.  
*	**Score 0** ( = ikke vurdert) brukes når det ikke er foretatt noen vurdering av denne aksen. 
*	**Score 1** ( = ingen) brukes når ingen <<oversikt-over-datasett, oversikt>> er <<tilgjengeliggjort, tilgjengeliggjort>> for eksterne brukere. Det kan skyldes av at den ikke finnes, eller at den ikke er tilgjengeliggjort for eksterne brukere.  
** Score 1 er eneste naturlig valg for Tilgjengelighet dersom <<aksen-dataoversikt, aksen Oversikt over datasett>> har score=0 eller 1. 
*	**Score 2** ( = ad hoc) brukes når (deler av eksisterende) <<oversikt-over-datasett, oversikt>> er <<tilgjengeliggjort, tilgjengeliggjort>> for eksterne brukere, dessuten kun på ad hoc basis.  
**	Denne lar seg greit kombinere med score 2, 3 og 4 for <<aksen-dataoversikt, aksen Oversikt over datasett>>.  
** Score 2 kan brukes når deler av (men ikke nødvendigvis hele) den eksisterende oversikten er tilgjengeliggjort på ad hoc basis, for eksterne brukere.  
** Eksempel på bruk av score 2: «Bare Prosjektet P (20xx-20yy) som beskrev hvilke datasett som inngikk i tjenestene som ble utviklet i prosjektet, publiserte oversikten sin eksternt. Oversikten er ikke blitt oppdatert siden da.» 
*	**Score 3** ( = noen) brukes når virksomheten <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort, tilgjengeliggjør>> <<oversikt-over-datasett, oversikten>> over noen (men ikke alle) <<relevante-datasett, relevante datasett>> for eksterne brukere.  
**	For å komme fra score 2 til score 3: Det holder med at <<oversikt-over-datasett, oversikten>> over minst ett datasett er <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort,tilgjengeliggjort>> for eksterne brukere.  
** Denne lar seg greit kombinere med score 3 og 4 for <<aksen-dataoversikt, aksen Oversikt over datasett>>, mens kombinasjon med score 2 virker unaturlig.  
** Eksempel på bruk av score 3: «Fagområde F har de siste 3 årene publisert årlig oversikten over datasett de forvalter, i samsvar med DCAT-AP-NO.» 
*	**Score 4** ( = alle) brukes når virksomheten systematisk tilgjengeliggjør oversikten over alle sine relevante datasett for eksterne brukere.  
**	For å komme fra score 3 til score 4: Virksomheten vurderer det slik at <<oversikt-over-datasett, oversikten>> over alle <<relevante-datasett, relevante datasett>> fra virksomheten er <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort,tilgjengeliggjort>> for eksterne brukere.  
** Kun kombinasjon med score 4 for <<aksen-dataoversikt, aksen Oversikt over datasett>> er naturlig.  
** Eksempel på bruk av score 4: «I forbindelse med risikovurdering i fjor kartla vi alle datasett i hele virksomheten. Oversikten er nå utformet i samsvar med DCAT-AP-NO og publisert på hjemmesiden. Seksjon S har fått ansvar for å oppdatere og publisere oversikten årlig.» 

=== Aksen Beskrivelse av datasett [[aksen-datasettbeskrivelse]]
*	Se Se https://www.digdir.no/informasjonsforvaltning/veileder-orden-i-eget-hus/2716[Veileder for orden i eget hus &#x29C9;, window="_blank", role="ext-link"], for forskjell og sammenheng mellom Oversikt over datasett og Beskrivelse av datasett.  
*	**Score 0** ( = ikke vurdert) brukes når det ikke er foretatt noen vurdering av denne aksen. 
* **Score 1** ( = ingen) brukes når virksomheten ikke har noen <<beskrivelse-av-datasett, beskrivelse>> av egne <<datasett, datasett>>.  
*	**Score 2** ( = ad hoc) brukes når virksomheten har <<beskrivelse-av-datasett, beskrevet>> (noen) <<datasett, datasett>>, men kun på ad hoc basis. 
**	Score 2 kan brukes når minst ett datasett er beskrevet, men ingen i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>. 
** Eksempel på bruk av score 2: «Ifm. ulike samhandlingsprosjekter med andre etater har vi beskrevet datasettene som vi utveksler andre med, i ulike former (Word, Excel, UML, XML osv.).» 
*	**Score 3** ( = noen) brukes når virksomheten har noen av sine <<relevante-datasett, relevante datasett>> <<beskrivelse-av-datasett, beskrevet>>, i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>.  
**	For å komme fra score 2 til score 3: Minst ett (selv om ikke alle) <<datasett, datasett>> er <<beskrivelse-av-datasett, beskrevet>> i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>.  
** Eksempel på bruk av score 3: «Fagområde F var den første som brukte malen M til å beskrive alle sine datasett, samt prosedyre R for å sikre at datasettbeskrivelsene blir oppdatert årlig. Mangler tilsvarende beskrivelse fra andre fagområder.» 
*	**Score 4** ( = alle) brukes når virksomheten har <<beskrivelse-av-datasett, beskrevet>> alle sine <<relevante-datasett, relevante datasett>>, i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>.  
**	For å komme fra score 3 til score 4: Alle datasett som virksomheten har vurdert som <<relevante-datasett, relevante datasett>>, er tilstrekkelig <<beskrivelse-av-datasett, beskrevet>>, i <<strukturert-form, strukturert form>> og <<systematisk-vedlikeholdt, systematisk vedlikeholdt>>.  
** Eksempel på bruk av score 4: «I forbindelse med risikovurdering i fjor kartla vi alle datasett i hele virksomheten. Datasettene i oversikten er nå også beskrevet i samsvar med malen M. Seksjon S har fått ansvar for årlig oppdatering av oversikten og beskrivelsene i oversikten.» 

=== Aksen Tilgjengelighet av beskrivelse av datasett [[aksen-tilgjengelighet-datasettbeskrivelse]]
*	Det er tilgjengeliggjøring av [.underline]#beskrivelse# av datasett denne aksen handler om, ikke tilgjengeliggjøring av selve datasettene. Det er dessuten tilgjengelighet for eksterne brukere det her spørres om.  
*	Det er avhengighet mellom <<aksen-datasettbeskrivelse, aksen Beskrivelse av datasett>> og denne aksen Tilgjengelighet av beskrivelse av datasett - dersom vi ikke har noen beskrivelse, har vi heller ingenting å tilgjengeliggjøre.  
*	**Score 0** ( = ikke vurdert) brukes når det ikke er foretatt noen vurdering av denne aksen. 
*	**Score 1** ( = ingen) brukes når virksomheten ikke har tilgjengeliggjort noen beskrivelse av egne datasett for eksterne brukere. Det kan skyldes av at det ikke finnes noen beskrivelse av datasett, eller at beskrivelsen ikke er tilgjengeliggjort for eksterne brukere.  
**	Score 1 er eneste naturlig valg for Tilgjengelighet dersom <<aksen-datasettbeskrivelse, aksen Beskrivelse av datasett>> har score=0 eller 1. 
*	**Score 2** ( = ad hoc) brukes når virksomheten har tilgjengeliggjort beskrivelse av noen (men ikke alle) <<relevante-datasett, relevante datasett>>, for eksterne brukere, kun på ad hoc basis.  
**	Score 2 kan brukes når beskrivelse av minst ett datasett er tilgjengeliggjort for eksterne brukere på ad hoc basis.  
** Denne lar seg greit kombinere med score 2, 3 og 4 for aksen Beskrivelse av datasett.  
** Eksempel på bruk av score 2: «Bare Prosjektet P (20xx-20yy) som beskrev hvilke datasett som inngikk i tjenestene som ble utviklet i prosjektet, publiserte beskrivelsene eksternt. Oversikten med beskrivelsene er ikke blitt oppdatert siden da.» 
*	**Score 3** ( = noen) brukes når virksomheten <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort, tilgjengeliggjør>> <<beskrivelse-av-datasett, beskrivelse>> av noen (men ikke alle) <<relevante-datasett, relevante datasett>> for eksterne brukere.  
**	For å komme fra score 2 til score 3: Når <<beskrivelse-av-datasett, beskrivelse>> av minst ett <<datasett, datasett>> er <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort, tilgjengeliggjort>> for eksterne brukere.  
** Denne lar seg greit kombinere med score 3 og 4 for <<aksen-datasettbeskrivelse, aksen Beskrivelse av datasett>>, mens kombinasjon med score 2 virker unaturlig.  
** Eksempel på bruk av score 3: «Fagområde F var den første som brukte malen M til å beskrive alle sine datasett som også ble publisert på hjemmesiden, samt prosedyre R for å sikre at datasettbeskrivelsene blir oppdatert og publisert årlig. Mangler tilsvarende beskrivelse fra andre fagområder.» 
*	**Score 4** ( = alle) brukes når virksomheten <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort, tilgjengeliggjør>> <<beskrivelse-av-datasett, beskrivelse>> av alle sine <<relevante-datasett, relevante datasett>> for eksterne brukere.  
**	For å komme fra score 3 til score 4: Virksomheten vurderer det slik at <<beskrivelse-av-datasett, beskrivelse>> av alle <<relevante-datasett, relevante datasett>> fra virksomheten er <<systematisk-vedlikeholdt, systematisk>> <<tilgjengeliggjort, tilgjengeliggjort>> for eksterne brukere.  
** Kun kombinasjon med score 4 for <<aksen-datasettbeskrivelse, aksen Beskrivelse av datasett>> er naturlig.  
** Eksempel på bruk av score 4: «I forbindelse med risikovurdering i fjor kartla vi alle datasett i hele virksomheten. Oversikten og beskrivelsen av datasettene i oversikten er publisert på hjemmesiden, i henhold til DCAT-AP-NO hhv. malen M. Seksjon S har fått ansvar for å oppdatere og publisere oversikten og datasettbeskrivelsene årlig.» 

=== Mal for dokumentasjon av modenhetsvurdering [[mal-for-dokumentasjon]]

.Mal for dokumentasjon av modenhetsvurdering
[frame=all, grid=all]
[cols="40s,10,10,20,20"]
|===
| Akse | Score | Mål | Problemer opplevd | Vurderinger gjort
| Prosedyrer | | | |
| Oversikt over datasett | | | |
| Tilgjengelighet av oversikt over datasett | | | |
| Beskrivelse av datasett | | | |
| Tilgjengelighet av beskrivelse av datasett | | | |
|===

Man bør foreta modenhetsvurdering jevnlig, f.eks. årlig. For at vurderingene skal kunne gjøres likt over tid, anbefaler vi å dokumentere følgende i tillegg til selve scorene:

*	Mål: Modenhetsnivået man ønsker å nå innen neste modenhetsvurdering. 
*	Problemer opplevd: Hva som oppleves vanskelig under vurderingen, f.eks.: forankring (bl.a. 
avsatt ressurs/tid til å foreta vurderingen), oversikt/innsikt som er nødvendig for å kunne foreta vurderingen, forståelse av begrepene/aksene/scorene som er brukt i modenhetsmodellen.  
** Innspill til å forbedre forklaring av begrepene/aksene/scorene bes meldes til Digdir som har ansvaret for vedlikehold av denne modellen.  
*	Vurderinger gjort: Hva som gjør at man velger den valgte scoren. f.eks.: hva er vurdert/definert som relevant, nødvendig og tilstrekkelig; hvilke krav (standard/prosedyre/mal) man vurderte mot. Se eksemplene foran under forklaring til den enkelte score langs de ulike aksene.  
