== Hensikten med modenhetsmodellen [[hensikt]]

Modellen skal brukes som et internt hjelpemiddel til å kartlegge modenhet hos de enkelte virksomhetene i offentlig sektor, både store og små, statlige og kommunale virksomheter.  
 
Hensikten med en modenhetsmodell er å hjelpe en virksomhet å vurdere hvor langt den er kommet iht. gitte kriterier (aksene i modellen), og til «selvutvikling». Ved gjentatte målinger/vurderinger kan en følge sin egen utvikling fra en nullpunktmåling og videre fram mot ønsket mål. I virksomheter der modenheten kan variere sterkt mellom ulike organisasjonsenheter, bør hver enhet vurderes for seg. En totalscore i form av snitt/median/e.l. av scorene fra de ulike organisasjonsenhetene, gir liten mening i en virksomhet av denne typen da den bare vil tilsløre viktige innspill til videre forbedringer. For å få overblikk over modenhet i ulike organisasjonsenheter, kan scorene fra de ulike organisasjonsenhetene sammenstilles i samme diagram.  
 
Modellen er ikke laget for sammenligning mellom virksomheter. 
 
Denne modenhetsmodellen har til hensikt å understøtte datadeling på tvers av virksomheter. I tillegg til evnen til systematisk å ha oversikt over og beskrivelse av egne data, måler derfor denne modellen også evnen til systematisk å gjøre tilgjengelig dataoversikten og databeskrivelsene for eksterne brukere, som gjør det lettere for andre å vite hva en har av data, hva dataene betyr, hva de kan brukes til osv.footnote:[Jf. også https://www.regjeringen.no/no/dokumenter/meld.-st.-27-20152016/id2483795/?q=&ch=2#kap7[kapittel 7 Informasjon til forvaltningen  skal leveres kun én gang    &#x29C9;, window="_blank", role="ext-link"] i Meld. St. 27 (2015–2016) - Digital agenda for Norge — IKT for en enklere hverdag og økt produktivitet.]  
