== Innledning [[innledning]]

Informasjon er en av de viktigste ressursene i offentlig sektor, og det har lenge vært et krav om at offentlig sektor må utnytte informasjonen sin på en bedre måte. Dette krever imidlertid en helhetlig forvaltning av informasjon på tvers av offentlige virksomheter, ikke minst også internt i den enkelte virksomheten («orden i eget hus»footnote:[Se https://www.digdir.no/informasjonsforvaltning/veileder-orden-i-eget-hus/2716[Veileder for orden i eget hus &#x29C9;, window="_blank", role="ext-link"]]). 
 
Dette dokumentet inneholder en modenhetsmodell for «orden i eget hus», med fokus på å ha oversikt over og beskrivelse av egne datasett. Med modenhet menes det her ikke bare å være moden, men ulik grad av modenhet, dvs. grad av å inneha gitte egenskaper. Etter hvert som vi får mer erfaring med bruken av modellen, og informasjonsforvaltning generelt, vil vi utvikle modenhetsmodellen videre.  
 
Dette dokumentet inneholder modenhetsmodellen og en bruksanvisning for hvordan man kan bruke modellen. I tillegg finnes en «Veileder for orden i eget hus» som eget dokument. Veilederen gir en bredere omtale av informasjonsforvaltning og bør brukes i kombinasjon med modenhetsmodellen. Dersom en f.eks. scorer lavt på en av aksene i modenhetsmodellen, skal veilederen bidra med råd om hvordan en kan forbedre denne scoren.  
