name: build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/modenhetsmodell.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      files: |
        docs/index.html text/html nb
        docs/files/modenhetsmodell.pdf application/pdf nb files/modenhetsmodell.pdf
        docs/files/modenhetsmodell-v1.xlsx application/vnd.openxmlformats-officedocument.spreadsheetml.sheet nb files/modenhetsmodell-v1.xlsx
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/illustrasjon-av-modenhetsmodellen.png image/png nb images/illustrasjon-av-modenhetsmodellen.png
      host: https://data.norge.no
      ontology: modenhetsmodell
      ontology-type: guide
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
